### ISSUE TITLE
Research Installing on Windows

### ISSUE THREAD

**Issue by JoshInnis** [AGEDB-INC/maria-server#12]
- What are the prerequisite to install the MariaDB on Windows.
- Document the procedure for installing MariaDB on Windows.

**Comment by arun-esh** [comment]
Went through the documentation and followed the instructions to install MariaDB on windows operating system. 
There are some pre-requisite which needs to be installed to specific locations and must be added to PATH environment.

**Comment by arun-esh** [comment]
I am also working on blog post which explains in details `How to install MariaDB on Windows` and will be raising Pull Request soon.

**Comment by arun-esh** [comment]
@JoshInnis 
I have just raised a PR #32 with all the details as per this issue. Please have a look at the PR as per your availability. Thanks
